---
  - name: Common > Create /opt directories for Kubernetes
    file:
      path: "{{ item }}"
      owner: "{{ infra_user }}"
      group: "{{ infra_group }}"
      state: directory
      mode: 0644
    with_items:
      - "{{ k8s_dir }}"

  - name: K8s > Add Kubernetes GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

  - name: K8s > Add Kubernetes APT repository
    apt_repository:
      repo: deb http://apt.kubernetes.io kubernetes-xenial main

  - name: K8s > Install Kubelet | Kubeadm | kubectl
    apt:
      pkg:
        - kubelet
        - kubeadm
        - kubectl
      state: present
      update_cache: yes
# when: "ansible_os_family == 'Debian'"

  - name: K8s > Prepare kubeadm config.yml
    template:
      src: 'kubeadm-init-config.yml.j2'
      dest: "{{ k8s_dir }}/kubeadm-init-config.yml"
      mode: 0644
      owner: root
      group: root
