---
  # - name: Kubectl > Kubectl package
  #   get_url:
  #     url: "{{ item }}"
  #     dest: "{{ download_dir }}/"
  #     mode: 0777
  #   with_items:
  #     - https://storage.googleapis.com/kubernetes-release/release/v1.10.1/bin/linux/amd64/kubectl
  #
  # - name:  Kubectl > Move kubectl to /usr/local/bin
  #   copy:
  #     src: "{{ download_dir }}/{{ item.src }}"
  #     dest: "/usr/local/bin/{{ item.dest }}"
  #     owner: root
  #     group: root
  #     mode: 0777
  #   with_items:
  #     - { src: kubectl, dest: kubectl }
