---

  - name: NFS > install NFS server
    package:
      name: "{{ item }}"
      state: present
    with_items:
     - "{{ nfs_packages.server }}"
    when: "'management' in group_names"

  - name: NFS > install NFS Client
    package:
      name: "{{ item }}"
      state: present
    with_items:
     - "{{ nfs_packages.client }}"

  - name: NFS > Create NFS Directory
    file:
      path: "{{ item }}"
      owner: nobody
      group: nogroup
      state: directory
      mode: 0777
      recurse: yes
    with_items:
      - "{{ nfs_dir }}"
    when: environment_requires_nfs_server and 'management' in group_names

  - name: NFS > Configure the exports file
    template:
      src: "exports.j2"
      dest: "/etc/exports"
      mode: 0644
      owner: root
      group: root
    when: environment_requires_nfs_server and 'management' in group_names

  - name: NFS > execute exportfs
    shell: exportfs -a
    when: environment_requires_nfs_server and 'management' in group_names

  - name: NFS > set mountpoints
    mount:
      name: /var/nfs/general
      src: k8s-hmrc-management:/var/nfs/general
      fstype: nfs
      opts: rw
      state: mounted
    when: environment_requires_nfs_server and 'management' not in group_names

# sudo mount 192.168.2.11:/var/nfs/general /var/nfs/general
# showmount -e 192.168.2.11
