- name: Infrastructure environment variables
  hosts: all
  tasks:
    - include: inventory-vars.yml
  tags:
    - env_vars


- name: Infrastructure Playbook
  import_playbook: assignments/all.yml
  tags:
    - playbooks
