---
  - name: ETCD > Create directories for the infrastructure
    file:
      path: "{{ item }}"
      owner: "{{ infra_user }}"
      group: "{{ infra_group }}"
      state: directory
      mode: 0744
      recurse: yes
    with_items:
      - "{{ etcd_dir }}"
      - "{{ etcd_lib_dir }}"

  - name: ETCD > Move the Kubernetes certificates to ETCD
    copy:
      src: "{{ item }}"
      dest: "{{ etcd_dir }}/"
      owner: root
      group: root
      mode: 0644
    with_fileglob:
      -  "{{ nfs_dir }}/*.pem"

  - name: ETCD > check if we need to download ETCD
    stat:
      path: /usr/local/bin/etcd
    register: etcd_sym

  - name: ETCD > Download and Extract ETCD Binaries to /tmp
    unarchive:
      src: https://github.com/coreos/etcd/releases/download/v3.3.9/etcd-v3.3.9-linux-amd64.tar.gz
      dest: /tmp/
      remote_src: yes
    register: etcd_extracted
    when: etcd_sym.stat.islnk is not defined

  - name: ETCD > Move ETCD Binaries to /usr/bin/local
    copy:
      src: "{{ item }}"
      dest: /usr/local/bin/
      owner: root
      group: root
    when: etcd_extracted.changed and etcd_sym.stat.islnk is not defined
    with_fileglob:
      -  /tmp/etcd-v3.3.9-linux-amd64

  - name: ETCD > Create symbolic link to etcd binary
    file:
      src: "{{ item.src }}"
      dest:  "{{ item.dest }}"
      state: link
    with_items:
      - { src: /usr/local/bin/etcd-v3.3.9-linux-amd64/etcd, dest: /usr/local/bin/etcd  }
      - { src: /usr/local/bin/etcd-v3.3.9-linux-amd64/etcdctl, dest: /usr/local/bin/etcdctl }

  - name: ETCD > Configure ETCD Systemd
    template:
      src: 'etcd.service.j2'
      dest: '/etc/systemd/system/etcd.service'
      mode: 0644
      owner: root
      group: root
    notify: start_up_etcd

  - name: ETCD > Export ETCDCTL environment variables
    lineinfile:
      path: /etc/profile
      line: |
          export ETCDCTL_API=3
          export ETCDCTL_ENDPOINTS="https://{{ hostvars[inventory_hostname]['ansible_enp0s8']['ipv4']['address']}}:2379"
          export ETCDCTL_CACERT="/etc/etcd/ca.pem"
          export ETCDCTL_CERT="/etc/etcd/kubernetes.pem"
          export ETCDCTL_KEY="/etc/etcd/kubernetes-key.pem"
