---
    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
        state: present
        update_cache: yes

    - name: Install list of packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          # - docker-ce="{{ docker_version }}~ce~3-0~{{ docker_linux_distribution }}"  -- Needs fixing...
        state: present
        update_cache: yes
